# Generated by Django 4.1 on 2024-01-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('hydrogen_concentration', models.FloatField()),
                ('smoke_concentration', models.FloatField()),
                ('rssi', models.IntegerField()),
                ('mac_address', models.CharField(max_length=17)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
