# Generated by Django 4.1 on 2024-01-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('uptime', models.IntegerField(blank=True, null=True)),
                ('clients_connected', models.IntegerField(blank=True, null=True)),
                ('messages_received', models.IntegerField(blank=True, null=True)),
                ('messages_sent', models.IntegerField(blank=True, null=True)),
                ('messages_stored', models.IntegerField(blank=True, null=True)),
                ('bytes_received', models.IntegerField(blank=True, null=True)),
                ('bytes_sent', models.IntegerField(blank=True, null=True)),
                ('subscriptions_count', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SysInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('payload', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
