# Generated by Django 4.1 on 2024-04-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_brokerinfo_sysinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='hydrogen_concentration',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='rssi',
        ),
    ]
