# Generated by Django 4.1 on 2024-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_remove_sensordata_hydrogen_concentration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSI_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_mac', models.CharField(max_length=17)),
                ('ap_mac', models.CharField(max_length=17)),
                ('rssi', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_mac', models.CharField(max_length=17)),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('human_detection', models.IntegerField()),
                ('hydrogen', models.IntegerField()),
                ('fire', models.IntegerField()),
                ('co', models.IntegerField()),
                ('smoke', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BrokerInfo',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.DeleteModel(
            name='SysInfo',
        ),
    ]
