# Generated by Django 4.1 on 2024-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_rssi_data_sensor_data_delete_brokerinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='humidity',
            field=models.FloatField(),
        ),
    ]
