# Generated by Django 4.1 on 2024-04-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_sensordata_rename_rssi_data_rssidata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
