# Generated by Django 4.1 on 2024-04-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_alter_sensordata_humidity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_mac', models.CharField(max_length=17)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hydrogen', models.IntegerField()),
                ('fire', models.IntegerField()),
                ('co', models.IntegerField()),
                ('smoke', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='RSSIData',
            new_name='RSSI_Data',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
