# Generated by Django 4.1 on 2024-04-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0008_sensor_data_rename_rssidata_rssi_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_data',
            name='human_detection',
            field=models.IntegerField(default=0),
        ),
    ]
