# Generated by Django 4.1 on 2024-06-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0010_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor_data',
            name='fire',
        ),
        migrations.RemoveField(
            model_name='sensor_data',
            name='human_detection',
        ),
        migrations.RemoveField(
            model_name='sensor_data',
            name='humidity',
        ),
    ]
