# Generated by Django 4.1 on 2024-06-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0011_remove_sensor_data_fire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
