# Generated by Django 4.1 on 2024-06-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0012_alter_sensor_data_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
